quotes = [
    {"id": 1, "author": "Linus Torvalds", "quote": "Talk is cheap. Show me the code."},
    {"id": 2, "author": "Grace Hopper", "quote": "The most dangerous phrase is 'we've always done it this way'."},
    {"id": 3, "author": "Donald Knuth", "quote": "Premature optimization is the root of all evil."},
    {"id": 4, "author": "Edsger Dijkstra", "quote": "Simplicity is prerequisite for reliability."},
    {"id": 5, "author": "Ken Thompson", "quote": "When in doubt, use brute force."},
    {"id": 6, "author": "Bjarne Stroustrup", "quote": "C makes it easy to shoot yourself in the foot; C++ makes it harder, but when you do, it blows away your whole leg."},
    {"id": 7, "author": "Brian Kernighan", "quote": "Debugging is twice as hard as writing the code in the first place."},
    {"id": 8, "author": "James Gosling", "quote": "Java is to JavaScript what car is to Carpet."},
    {"id": 9, "author": "Yukihiro Matsumoto", "quote": "Matz is nice and so we are nice."},
    {"id": 10, "author": "Tim Berners-Lee", "quote": "The Web does not just connect machines, it connects people."},
    {"id": 11, "author": "Alan Kay", "quote": "The best way to predict the future is to invent it."},
    {"id": 12, "author": "Fred Brooks", "quote": "Adding manpower to a late software project makes it later."},
    {"id": 13, "author": "Martin Fowler", "quote": "Any fool can write code that a computer can understand. Good programmers write code that humans can understand."},
    {"id": 14, "author": "Robert Martin", "quote": "Clean code always looks like it was written by someone who cares."},
    {"id": 15, "author": "John Carmack", "quote": "Focused, hard work is the real key to success."},
    {"id": 16, "author": "Larry Wall", "quote": "The three chief virtues of a programmer are: Laziness, Impatience and Hubris."},
    {"id": 17, "author": "Dennis Ritchie", "quote": "UNIX is basically a simple operating system, but you have to be a genius to understand the simplicity."},
    {"id": 18, "author": "Alan Turing", "quote": "We can only see a short distance ahead, but we can see plenty there that needs to be done."},
    {"id": 19, "author": "Guido van Rossum", "quote": "Python is an experiment in how much freedom programmers need."},
    {"id": 20, "author": "Rich Hickey", "quote": "Programming is not about typing, it's about thinking."},
    {"id": 21, "author": "Ward Cunningham", "quote": "The best programs are written when the programmer is supposed to be working on something else."},
    {"id": 22, "author": "Jeff Atwood", "quote": "Code tells you how, comments tell you why."},
    {"id": 23, "author": "Joel Spolsky", "quote": "Good software, like wine, takes time."},
    {"id": 24, "author": "Paul Graham", "quote": "A programming language is for thinking about programs, not for expressing programs you've already thought of."},
    {"id": 25, "author": "Eric Raymond", "quote": "Given enough eyeballs, all bugs are shallow."},
    {"id": 26, "author": "Grady Booch", "quote": "The function of good software is to make the complex appear to be simple."},
    {"id": 27, "author": "Kent Beck", "quote": "I'm not a great programmer; I'm just a good programmer with great habits."},
    {"id": 28, "author": "John Johnson", "quote": "First, solve the problem. Then, write the code."},
    {"id": 29, "author": "Steve McConnell", "quote": "Good code is its own best documentation."},
    {"id": 30, "author": "Anonymous", "quote": "There are only two hard things in Computer Science: cache invalidation and naming things."},
    {"id": 31, "author": "Jamie Zawinski", "quote": "Some people, when confronted with a problem, think 'I know, I'll use regular expressions.' Now they have two problems."},
    {"id": 32, "author": "Tony Hoare", "quote": "There are two ways of constructing software: make it so simple there are obviously no deficiencies, or make it so complicated that there are no obvious deficiencies."},
    {"id": 33, "author": "Peter Norvig", "quote": "Debugging is like being a detective in a crime movie where you are also the murderer."},
    {"id": 34, "author": "Andy Hunt", "quote": "No one in the brief history of computing has ever written a piece of perfect software."},
    {"id": 35, "author": "Dave Thomas", "quote": "The greatest enemy of knowledge is not ignorance, it is the illusion of knowledge."},
    {"id": 36, "author": "Alan Perlis", "quote": "A language that doesn't affect the way you think about programming is not worth knowing."},
    {"id": 37, "author": "Michael Feathers", "quote": "Code without tests is bad code. It doesn't matter how well written it is."},
    {"id": 38, "author": "Kevlin Henney", "quote": "The code you write makes you a programmer. The code you delete makes you a good one."},
    {"id": 39, "author": "Douglas Crockford", "quote": "JavaScript is the world's most misunderstood programming language."},
    {"id": 40, "author": "Ryan Dahl", "quote": "I hate almost all software. It's unnecessary and complicated at almost every layer."},
    {"id": 41, "author": "John Ousterhout", "quote": "The greatest limitation in writing software is our ability to understand the systems we create."},
    {"id": 42, "author": "Brendan Eich", "quote": "Always bet on JavaScript."},
    {"id": 43, "author": "Anders Hejlsberg", "quote": "A good programming language is a conceptual universe for thinking about programming."},
    {"id": 44, "author": "Addy Osmani", "quote": "First do it, then do it right, then do it better."},
    {"id": 45, "author": "Uncle Bob Martin", "quote": "Truth can only be found in one place: the code."},
    {"id": 46, "author": "Hal Abelson", "quote": "Programs must be written for people to read, and only incidentally for machines to execute."},
    {"id": 47, "author": "Gerald Sussman", "quote": "We are trying to understand and organize complexity."},
    {"id": 48, "author": "Niklaus Wirth", "quote": "A good designer must rely on experience, on precise, logic thinking; and on pedantic exactness."},
    {"id": 49, "author": "Butler Lampson", "quote": "All problems in computer science can be solved with another level of indirection."},
    {"id": 50, "author": "David Wheeler", "quote": "Compatibility means deliberately repeating other people's mistakes."},
    {"id": 51, "author": "Jon Bentley", "quote": "The cheapest, fastest and most reliable components of a computer system are those that aren't there."},
    {"id": 52, "author": "Kristen Nygaard", "quote": "Programming is understanding."},
    {"id": 53, "author": "Ole-Johan Dahl", "quote": "A program is never less than 90% complete, and never more than 95% complete."},
    {"id": 54, "author": "Marvin Minsky", "quote": "You don't understand anything until you learn it more than one way."},
    {"id": 55, "author": "John von Neumann", "quote": "In mathematics you don't understand things. You just get used to them."},
    {"id": 56, "author": "Seymour Cray", "quote": "The trouble with programmers is that you can never tell what a programmer is doing until it's too late."},
    {"id": 57, "author": "Bill Gates", "quote": "Measuring programming progress by lines of code is like measuring aircraft building progress by weight."},
    {"id": 58, "author": "Steve Jobs", "quote": "Everybody should learn to program a computer, because it teaches you how to think."},
    {"id": 59, "author": "Elon Musk", "quote": "It's OK to have your eggs in one basket as long as you control what happens to that basket."},
    {"id": 60, "author": "Mark Zuckerberg", "quote": "The biggest risk is not taking any risk."},
    {"id": 61, "author": "Jeff Bezos", "quote": "I knew that if I failed I wouldn't regret that, but I knew the one thing I might regret is not trying."},
    {"id": 62, "author": "Larry Page", "quote": "Always deliver more than expected."},
    {"id": 63, "author": "Sergey Brin", "quote": "Obviously everyone wants to be successful, but I want to be looked back on as being very innovative."},
    {"id": 64, "author": "Jack Dorsey", "quote": "Make every detail perfect and limit the number of details to perfect."},
    {"id": 65, "author": "Reed Hastings", "quote": "Do not tolerate brilliant jerks. The cost to teamwork is too high."},
    {"id": 66, "author": "Marc Benioff", "quote": "The only constant in the technology industry is change."},
    {"id": 67, "author": "Eric Schmidt", "quote": "We run this company on questions, not answers."},
    {"id": 68, "author": "Satya Nadella", "quote": "Our industry does not respect tradition - it only respects innovation."},
    {"id": 69, "author": "Tim Cook", "quote": "You can only do so many things great, and you should cast aside everything else."},
    {"id": 70, "author": "Sundar Pichai", "quote": "Wear your failure as a badge of honor."},
    {"id": 71, "author": "Sheryl Sandberg", "quote": "Done is better than perfect."},
    {"id": 72, "author": "Susan Wojcicki", "quote": "Think about what you want to learn, then make the commitment to learn it."},
    {"id": 73, "author": "Ginni Rometty", "quote": "Growth and comfort do not coexist."},
    {"id": 74, "author": "Safra Catz", "quote": "You have to be willing to be misunderstood if you're going to innovate."},
    {"id": 75, "author": "Diane Greene", "quote": "I think the key is just to focus on creating great products."},
    {"id": 76, "author": "Marissa Mayer", "quote": "I always did something I was a little not ready to do."},
    {"id": 77, "author": "Reshma Saujani", "quote": "We have to teach girls bravery instead of perfection."},
    {"id": 78, "author": "Kiran Mazumdar-Shaw", "quote": "I think leadership is about having a vision and being able to articulate that."},
    {"id": 79, "author": "Arianna Huffington", "quote": "We need to accept that we won't always make the right decisions."},
    {"id": 80, "author": "Reid Hoffman", "quote": "Starting a company is like jumping off a cliff and assembling a plane on the way down."},
    {"id": 81, "author": "Peter Thiel", "quote": "We wanted flying cars, instead we got 140 characters."},
    {"id": 82, "author": "Marc Andreessen", "quote": "Software is eating the world."},
    {"id": 83, "author": "Ben Horowitz", "quote": "The story must explain at a fundamental level why you exist."},
    {"id": 84, "author": "Naval Ravikant", "quote": "Seek wealth, not money or status."},
    {"id": 85, "author": "Paul Buchheit", "quote": "Ideas are cheap. Execution is everything."},
    {"id": 86, "author": "Drew Houston", "quote": "Don't worry about failure; you only have to be right once."},
    {"id": 87, "author": "Brian Chesky", "quote": "Build something 100 people love, not something 1 million people kind of like."},
    {"id": 88, "author": "Joe Gebbia", "quote": "An idea can turn to dust or magic, depending on the talent that rubs against it."},
    {"id": 89, "author": "Nathan Blecharczyk", "quote": "Culture is about empowering others to be their best."},
    {"id": 90, "author": "Stewart Butterfield", "quote": "The best way to make your dreams come true is to wake up."},
    {"id": 91, "author": "Daniel Ek", "quote": "I had two passions growing up - one was music, one was technology."},
    {"id": 92, "author": "Evan Spiegel", "quote": "People are going to copy your product if you build great stuff."},
    {"id": 93, "author": "Bobby Murphy", "quote": "We're trying to build something that's going to be around for a long time."},
    {"id": 94, "author": "Kevin Systrom", "quote": "I try to find the right balance between perfectionism and getting things done."},
    {"id": 95, "author": "Mike Krieger", "quote": "The best products come from a deep understanding of user needs."},
    {"id": 96, "author": "Jan Koum", "quote": "I only have one phone. I just really hate phones."},
    {"id": 97, "author": "Brian Acton", "quote": "Respect the user's time, attention, and peace of mind."},
    {"id": 98, "author": "Palmer Luckey", "quote": "The closer to reality you get, the more immersive it becomes."},
    {"id": 99, "author": "John Carmack", "quote": "Story in a game is like a story in a porn movie. It's expected to be there, but it's not that important."},
    {"id": 100, "author": "Gabe Newell", "quote": "The easiest way to stop piracy is not by putting antipiracy technology to work. It's by giving those people a service that's better than what they're receiving from the pirates."}
]